# Generated by Django 4.2.6 on 2024-01-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="category",
            field=models.CharField(
                choices=[("color", "Color"), ("verb", "Verb")],
                default="color",
                max_length=5,
            ),
        ),
    ]
