# Generated by Django 4.2.6 on 2024-01-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0002_word_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="theme",
            field=models.CharField(
                choices=[
                    ("colours", "Colours"),
                    ("town", "Town"),
                    ("kitchen", "Kitchen"),
                    ("pencase", "Pencase"),
                    ("fruits", "Fruits"),
                    ("objects", "Objects"),
                    ("pets", "Pets"),
                    ("school", "School"),
                    ("summer", "Summer"),
                ],
                default="colours",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="category",
            field=models.CharField(
                choices=[("noun", "Noun"), ("verb", "Verb")],
                default="noun",
                max_length=100,
            ),
        ),
    ]
